// Skills 数据（供网站展示）
window.SKILLS = [
  {
    icon: "🎯",
    name: "AI 需求价值判断",
    en: "ai-value-judge",
    type: "AI 产品",
    desc: "用通用价值公式 + AI 特有五问，判断一个 AI 功能值不值得做",
    repo: "https://github.com/macistone71-jpg/value-judgment-skill",
  },
  {
    icon: "🧩",
    name: "需求分析五步法",
    en: "requirement-analyzer",
    type: "产品",
    desc: "把模糊需求拆成可交付方案：用户-场景-问题 → 问题vs方案 → 价值 → 指标 → 文档",
    repo: "https://github.com/macistone71-jpg/requirement-analysis-skill",
  },
  {
    icon: "📚",
    name: "AI 备课工作流",
    en: "ai-lesson-planner",
    type: "AI + 教育",
    desc: "人机协作备课：AI 生成大纲、教案、讲稿初稿，人做审核和打磨",
    repo: "https://github.com/macistone71-jpg/course-design-skill",
  },
  {
    icon: "🔍",
    name: "竞品分析",
    en: "competitive-analyzer",
    type: "产品",
    desc: "看清市场分层，按四维度拆解竞品，落到「我们该怎么做」",
    repo: "https://github.com/macistone71-jpg/competitive-analysis-skill",
  },
  {
    icon: "🎙️",
    name: "讲解脚本",
    en: "lesson-script",
    type: "线上教育",
    desc: "用钩子-讲解-案例-练习-总结五段式，把知识点写成能录制的讲稿",
    repo: "https://github.com/macistone71-jpg/script-writing-skill",
  },
  {
    icon: "📝",
    name: "产品复盘",
    en: "launch-retrospective",
    type: "产品",
    desc: "用复盘五问把做对的、做错的、下次怎么改想清楚",
    repo: "https://github.com/macistone71-jpg/product-review-skill",
  },
  {
    icon: "✅",
    name: "笔记转 AI 考试",
    en: "ai-quiz-generator",
    type: "AI + 教育",
    desc: "把课堂笔记交给 AI，自动生成线上考试链接，打通学-测-反馈闭环",
    repo: "https://github.com/macistone71-jpg/learning-assessment-skill",
  },
];
