// Skills 数据（供网站展示）
window.SKILLS = [
  {
    icon: "🎯",
    name: "价值判断",
    en: "value-judge",
    type: "产品",
    desc: "用「用户价值 = 新体验 - 旧体验 - 替换成本」公式判断需求值不值得做",
    repo: "https://github.com/macistone71-jpg/value-judgment-skill",
  },
  {
    icon: "🧩",
    name: "需求分析五步法",
    en: "requirement-analyzer",
    type: "产品",
    desc: "把模糊需求拆成可交付方案：用户-场景-问题 → 问题vs方案 → 价值 → 指标 → 文档",
    repo: "https://github.com/macistone71-jpg/requirement-analysis-skill",
  },
  {
    icon: "📚",
    name: "课程设计",
    en: "course-designer",
    type: "线上教育",
    desc: "把一个知识主题设计成结构清晰、能落地交付的线上课程",
    repo: "https://github.com/macistone71-jpg/course-design-skill",
  },
  {
    icon: "🔍",
    name: "竞品分析",
    en: "competitive-analyzer",
    type: "产品",
    desc: "看清市场分层，按四维度拆解竞品，落到「我们该怎么做」",
    repo: "https://github.com/macistone71-jpg/competitive-analysis-skill",
  },
  {
    icon: "🎙️",
    name: "讲解脚本",
    en: "lesson-script",
    type: "线上教育",
    desc: "用钩子-讲解-案例-练习-总结五段式，把知识点写成能录制的讲稿",
    repo: "https://github.com/macistone71-jpg/script-writing-skill",
  },
  {
    icon: "📝",
    name: "产品复盘",
    en: "launch-retrospective",
    type: "产品",
    desc: "用复盘五问把做对的、做错的、下次怎么改想清楚",
    repo: "https://github.com/macistone71-jpg/product-review-skill",
  },
  {
    icon: "✅",
    name: "学习评估",
    en: "learning-assessment",
    type: "线上教育",
    desc: "设计能检验学习效果的作业、测验和练习",
    repo: "https://github.com/macistone71-jpg/learning-assessment-skill",
  },
];
